### ISSUE TITLE
Android 9 InvalidKeyException: unknown key type passed to RSA

### ISSUE THREAD

**Issue by zakrodionov** [cloudpayments/CloudPayments_AndroidCheckout#4]
При создании криптограммы такая ошибка

` java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.security.InvalidKeyException: unknown key type passed to RSA
        at com.android.org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineInit(CipherSpi.java:302)
        at com.android.org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineInit(CipherSpi.java:406)
        at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2984)
        at javax.crypto.Cipher.tryCombinations(Cipher.java:2877)
        at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
        at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
        at javax.crypto.Cipher.init(Cipher.java:1143)
        at ru.cloudpayments.cpcard.CPCard.cardCryptogram(CPCard.java:154)
        at ru.cloudpayments.cpcard.CPCard.cardCryptogram(CPCard.java:126)
        at .generateCrypto(NewCardFragment.kt:243)
        at .fetchData(NewCardFragment.kt:129)
        at prepareUi$3.onClick(NewCardFragment.kt:72)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25889)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)`

**Comment by zakrodionov** [comment]
Upd. При замене .aar, Gradle почему-то брал данные из старого.
Починилось удалением, Clean Project, Invalidate & Restart cache
